FROM cypress/included:latest
WORKDIR /test
COPY ./cypress ./cypress
COPY package.json package.json
COPY cypress.config.js cypress.config.js
RUN npm install
CMD ["node", "npx cypress run --env TEST_ENV=qa"]