# This is a basic workflow to help you get started with Actions

name: Run Cypress Release Regression Testing

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      testRelease:
        description: 'Release number'
        type: string
      testEnv:
        description: 'Selects the environment'
        required: true
        type: choice
        default: 'qa'
        options:
          - dev
          - qa
          - uat
jobs:

  build:
    runs-on: ubuntu-latest
    env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          TEST_RELEASE: ${{ github.event.inputs.testRelease }} 
          TEST_ENV: ${{ github.event.inputs.testEnv }} 
    steps:
      - uses: actions/checkout@v3
      - name: installing dependencies
        run: npm install
      - name: Generating the browserfile local        
        run: node ./cypress/utils/generateBrowserstackConfig.ts
      - name: Running test cases in browserstack        
        run: ./node_modules/.bin/browserstack-cypress run --env=$TEST_ENV
